/* PEPMOSA admin repair layer: GB cleanup + admin-fee approval workflow. */
(function(){
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),peso=v=>'₱'+Number(v||0).toLocaleString('en-PH',{minimumFractionDigits:2}),S=()=>window.sb||window.__sb;
async function deleteGB(g){if(!g)return;if(!confirm(`DELETE ${g}?\n\nThis permanently deletes ALL data belonging to this Group Buy, including admin-fee payments, orders, order items, GB categories, minimums, kit inventory and reservations.\n\nCustomer records themselves will NOT be deleted.\n\nTHIS CANNOT BE UNDONE.`))return;const s=S();if(!s)return alert('Supabase is not initialized. Please refresh.');try{const os=await s.from('orders').select('order_id').eq('gb_number',g);if(os.error)throw os.error;const ids=(os.data||[]).map(x=>x.order_id);if(ids.length){let r=await s.from('order_items').delete().in('order_id',ids);if(r.error)throw r.error;for(const t of ['tracking','waybills','shipments']){r=await s.from(t).delete().in('order_id',ids);if(r.error&&!/does not exist|relation .* does not exist/i.test(r.error.message||''))throw r.error}r=await s.from('orders').delete().in('order_id',ids);if(r.error)throw r.error}for(const [t,c] of [['kit_reservations','gb_number'],['kit_inventory','gb_number'],['admin_fee_payments','gb_number'],['gb_minimum_quantities','gb_number'],['gb_categories','gb_number']]){const r=await s.from(t).delete().eq(c,g);if(r.error&&!/does not exist|relation .* does not exist/i.test(r.error.message||''))throw r.error}const r=await s.from('group_buys').delete().eq('gb_number',g);if(r.error)throw r.error;if(typeof window.loadGroupBuys==='function')await window.loadGroupBuys();else if(typeof window.renderGroupBuys==='function')await window.renderGroupBuys();alert(`${g} and all related records were deleted.`)}catch(e){console.error(e);alert('DELETE FAILED: '+(e.message||e))}}
window.pepDeleteGB=deleteGB;
async function renderFeesFix(){const box=$('feeList');if(!box)return;const s=S();if(!s){box.innerHTML='<div class="notice error">Supabase is not initialized.</div>';return}box.innerHTML='Loading…';const q=($('feeSearch')?.value||'').trim().toLowerCase();let query=s.from('admin_fee_payments').select('*').order('created_at',{ascending:false}).limit(200);if(q)query=query.or(`email.ilike.%${q}%,full_name.ilike.%${q}%,telegram_name.ilike.%${q}%,phone.ilike.%${q}%`);const {data,error}=await query;if(error){box.innerHTML='<div class="notice error">Admin fee table is not ready.</div>';return}if(!(data||[]).length){box.innerHTML='<div class="empty">No admin fee payments yet.</div>';return}box.innerHTML=data.map(x=>{const st=x.status||'SUBMITTED';return `<div class="item"><div class="itemHead"><div><b>${esc(x.full_name||'No name')}</b><div class="small">Telegram: ${esc(x.telegram_name||'—')} • ${esc(x.phone||'—')}</div><div class="small">${esc(x.gb_number)} • ${peso(x.amount)} • ${new Date(x.created_at).toLocaleString('en-PH')}</div><div class="small">Email: ${esc(x.email||'Not verified yet')}</div>${x.payment_proof_url?`<div style="margin-top:10px"><a href="${esc(x.payment_proof_url)}" target="_blank" rel="noopener"><img src="${esc(x.payment_proof_url)}" alt="Payment proof" style="max-width:280px;max-height:220px;object-fit:contain;border:1px solid #ead9e4;border-radius:12px"></a></div>`:'<div class="small">Payment proof: missing</div>'}</div><span class="badge ${st==='PAID'?'green':st==='REJECTED'?'red':'yellow'}">${esc(st==='SUBMITTED'?'PENDING':st)}</span></div>${st==='SUBMITTED'?`<div class="actions"><button class="btn success" onclick="window.pepSetFeeStatus('${esc(x.id)}','PAID')">APPROVE PAYMENT</button><button class="btn danger" onclick="window.pepSetFeeStatus('${esc(x.id)}','REJECTED')">REJECT</button></div>`:''}</div>`}).join('')}
window.pepSetFeeStatus=async function(id,status){const s=S();if(!s)return;if(!confirm((status==='PAID'?'APPROVE':'REJECT')+' this admin fee payment?'))return;const r=await s.from('admin_fee_payments').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)alert(r.error.message);else{await renderFeesFix();if(status==='PAID')alert('Admin fee approved. Customer can now verify their email and continue ordering.')}};
window.renderFees=renderFeesFix;
function addGBDeleteButtons(){const list=$('gbList');if(!list)return;list.querySelectorAll('.item').forEach(item=>{if(item.querySelector('.pepDeleteGBBtn'))return;const m=(item.textContent||'').match(/\b(GB[-\w]+)\b/);if(!m)return;const actions=item.querySelector('.actions')||item.appendChild(Object.assign(document.createElement('div'),{className:'actions'}));const b=document.createElement('button');b.className='btn danger pepDeleteGBBtn';b.textContent='DELETE GB';b.onclick=()=>deleteGB(m[1]);actions.appendChild(b)})}

/* Current database has one explicit product_variants -> products FK. PostgREST can still report an ambiguous embed because other tables reference both products and variants. Use the FK name explicitly. */
async function loadProductsFixed(){const s=S();if(!s)throw new Error('Supabase is not initialized.');const {data,error}=await s.from('products').select('*, product_variants!product_variants_product_id_fkey(*)').order('product_name');if(error)throw error;window.products=data||[];if(typeof window.renderProducts==='function')window.renderProducts();}
window.loadProducts=loadProductsFixed;

/* The live schema uses gb_minimum_quantities (GB + product + variant), not the old gb_category_settings table. The category UI remains category-level by applying one minimum to every active variant in that category. */
async function loadCategoryMinimumsFixed(){const s=S(),gb=$("minimumGB")?.value;if(!s)throw new Error('Supabase is not initialized.');if(!gb){$("minimumList").innerHTML='Select a Group Buy.';return;}const {data:ps,error:pe}=await s.from('products').select('product_id,product_name,category,active,product_variants!product_variants_product_id_fkey(variant_id,strength,active)').eq('active',true).order('product_name');if(pe)throw pe;const {data:ms,error:me}=await s.from('gb_minimum_quantities').select('product_id,variant_id,minimum_qty').eq('gb_number',gb);if(me)throw me;const mins=ms||[];const activeCats=[...new Set((ps||[]).map(p=>p.category).filter(Boolean))];$("minimumList").innerHTML=activeCats.length?activeCats.map(cat=>{const variants=(ps||[]).filter(p=>p.category===cat).flatMap(p=>(p.product_variants||[]).filter(v=>v.active).map(v=>({product_id:p.product_id,variant_id:v.variant_id,product_name:p.product_name,strength:v.strength})));const values=variants.map(v=>{const x=mins.find(m=>m.product_id===v.product_id&&m.variant_id===v.variant_id);return x?Number(x.minimum_qty):1;});const value=values.length?Math.max(1,Math.min(...values)):1;return `<div class="categoryLine"><div><b>${esc(cat)}</b><div class="small">Applied to all active product variants in this category (${variants.length} variants)</div></div><input class="categoryMinimum" data-category="${esc(cat)}" type="number" min="1" value="${value}"></div>`}).join(''):'<div class="empty">No active product categories yet.</div>';}
window.loadCategoryMinimums=loadCategoryMinimumsFixed;
async function saveCategoryMinimumsFixed(){const s=S(),gb=$("minimumGB")?.value;if(!s)throw new Error('Supabase is not initialized.');if(!gb)return showMessage('Select a Group Buy first.','error');try{const {data:ps,error:pe}=await s.from('products').select('product_id,category,active,product_variants!product_variants_product_id_fkey(variant_id,active)').eq('active',true);if(pe)throw pe;for(const i of document.querySelectorAll('.categoryMinimum')){const qty=Math.max(1,Number(i.value||1)),cat=i.dataset.category;const rows=(ps||[]).filter(p=>p.category===cat).flatMap(p=>(p.product_variants||[]).filter(v=>v.active).map(v=>({gb_number:gb,product_id:p.product_id,variant_id:v.variant_id,minimum_qty:qty})));if(rows.length){const {error}=await s.from('gb_minimum_quantities').upsert(rows,{onConflict:'gb_number,product_id,variant_id'});if(error)throw error;}}await loadCategoryMinimumsFixed();showMessage('Category minimums saved.','success');}catch(e){console.error(e);showMessage(e.message||'Unable to save minimums.','error')}}
window.saveCategoryMinimums=saveCategoryMinimumsFixed;

/* Fix category delete to use the live minimum table. */
window.deleteCategory=async function(categoryName){if(!categoryName||!confirm(`DELETE CATEGORY "${categoryName}"?\n\nProducts using this category will NOT be deleted. Continue?`))return;try{const s=S();const {data:used,error:ue}=await s.from('products').select('product_id').eq('category',categoryName).limit(1);if(ue)throw ue;if((used||[]).length)return showMessage(`Cannot delete "${categoryName}" because products are still using it.`,'error');const {error:ce}=await s.from('categories').delete().eq('category_name',categoryName);if(ce)throw ce;await s.from('gb_categories').delete().eq('category_name',categoryName);await s.from('gb_minimum_quantities').delete().in('product_id',[]);await loadCategories();showMessage(`Category "${categoryName}" deleted successfully.`,'success');}catch(e){console.error(e);showMessage(e.message||'Unable to delete category.','error')}};

function boot(){let n=0;const t=setInterval(()=>{if(S()&&$('adminApp')){clearInterval(t);const ft=document.querySelector('[data-panel="feesPanel"]');if(ft)ft.addEventListener('click',()=>setTimeout(renderFeesFix,50));if($('feeSearch'))$('feeSearch').addEventListener('input',renderFeesFix);const l=$('gbList');if(l)new MutationObserver(addGBDeleteButtons).observe(l,{childList:true,subtree:true});setTimeout(addGBDeleteButtons,500);/* If the initial session loaded before this repair script arrived, retry the complete admin load now. */if($('adminApp').style.display!=='none'&&typeof window.loadEverything==='function'){setTimeout(()=>window.loadEverything().catch(e=>{console.error(e)}),150);}}if(++n>120)clearInterval(t)},100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();